#!/bin/bash
	
#cryptopp
export CRYPTO_PP_DIR="./cryptopp560"

#no need to check anything since make will just see that nothing has changed
cd $CRYPTO_PP_DIR
make
cd ..

#zookeeper
export ZOOKEEPER_BIN="./zookeeper_install"
export ZOOKEEPER_DIR="./zookeeper-3.1.1"

if [ ! -d "$ZOOKEEPER_BIN" ]; then
	mkdir -p $ZOOKEEPER_BIN
	cd $ZOOKEEPER_DIR"/src/c"
	./configure --prefix=$PWD"/../../../"$ZOOKEEPER_BIN && make && make install
	cd ../../..
fi

#gmp (a dependency of sfslite)
export GMP_BIN="./gmp_install"
export GMP_DIR="./gmp-4.3.1"

if [ ! -d "$GMP_BIN" ]; then
	mkdir -p $GMP_BIN
	cd $GMP_DIR
	./configure --prefix=$PWD"/../"$GMP_BIN && make && make install
	if [ $? -ne 0 ]; then
		cd ..
		rmdir $GMP_BIN
		exit 1
	fi
	cd ..
fi

#sfslite
export SFS_BIN="./sfs_install"
export SFS_DIR="./sfslite-1.2.7"

if [ ! -d "$SFS_BIN" ]; then
	mkdir -p $SFS_BIN
	cd $SFS_DIR
	sh -x setup.gnu -f -i -s && ./configure --with-gmp=$PWD"/../"$GMP_BIN --prefix=$PWD"/../"$SFS_BIN && gmake && gmake install
	if [ $? -ne 0 ]; then
		cd ..
		rmdir $SFS_BIN
		exit 1
	fi
	cd ..
fi

#log4cpp
export LOG4CPP_BIN="./log4cpp_install"
export LOG4CPP_DIR="./log4cpp-1.0"

if [ ! -d "$LOG4CPP_BIN" ]; then
	mkdir -p $LOG4CPP_BIN
	cd $LOG4CPP_DIR
	./configure --prefix=$PWD"/../"$LOG4CPP_BIN && make && make check && make install
	if [ $? -ne 0 ]; then
		cd ..
		rmdir $LOG4CPP_BIN
		exit 1
	fi
	cd ..
fi

#libconfig
export LIBCONFIG_BIN="./libconfig_install"
export LIBCONFIG_DIR="./libconfig-1.4.2"

if [ ! -d "$LIBCONFIG_BIN" ]; then
	mkdir -p $LIBCONFIG_BIN
	cd $LIBCONFIG_DIR
	./configure --prefix=$PWD"/../"$LIBCONFIG_BIN && make && make check && make install
	if [ $? -ne 0 ]; then
		cd ..
		rmdir $LIBCONFIG_BIN
		exit 1
	fi
	cd ..
fi

#lighttpd
export LIGHTTPD_BIN="./lighttpd_install"
export LIGHTTPD_DIR="./lighttpd-1.4.26"

if [ ! -d "$LIGHTTPD_BIN" ]; then
	mkdir -p $LIGHTTPD_BIN
	cd $LIGHTTPD_DIR
	./configure --prefix=$PWD"/../"$LIGHTTPD_BIN && make && make install
	if [ $? -ne 0 ]; then
		cd ..
		rmdir $LIGHTTPD_BIN
		exit 1
	fi
	cd ..
fi

